ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '123456';
CREATE DATABASE IF NOT EXISTS mall DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS mall_ads DEFAULT CHARACTER SET utf8mb4;
CREATE USER IF NOT EXISTS 'datax'@'%' IDENTIFIED BY '123456';
GRANT SELECT ON mall.* TO 'datax'@'%';
GRANT SELECT,INSERT,UPDATE ON mall_ads.* TO 'datax'@'%';
FLUSH PRIVILEGES;
SHOW DATABASES;
