DROP DATABASE IF EXISTS test;
CREATE DATABASE mall;
CREATE TABLE IF NOT EXISTS mall.user_info (
  user_id STRING,
  user_name STRING,
  age INT,
  gender STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;
